/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>

int *
suma_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a + argp->b;

	return &result;
}

int *
resta_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a - argp->b;

	return &result;
}

int *
multiplica_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a * argp->b;

	return &result;
}

double *
divide_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	if (argp->b == 0) {
		result = NAN;
	} else {
		result = (double)argp->a / (double)argp->b;
	}

	return &result;
}
