/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>


void
cal_prog_1(char *host)
{
	CLIENT *clnt;
	operandos args;
	int operacion;
	int a, b;

#ifndef	DEBUG
	clnt = clnt_create (host, CAL_PROG, CAL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("=== CALCULADORA RPC ===\n");
	printf("Operaciones disponibles:\n");
	printf("1. Suma\n");
	printf("2. Resta\n");
	printf("3. Multiplicación\n");
	printf("4. División\n");
	printf("0. Salir\n\n");

	while (1) {
		printf("Selecciona operación (0-4): ");
		scanf("%d", &operacion);
		
		if (operacion == 0) {
			printf("Saliendo...\n");
			break;
		}
		
		if (operacion < 1 || operacion > 4) {
			printf("Operación inválida. Intenta de nuevo.\n");
			continue;
		}
		
		printf("Ingresa el primer número: ");
		scanf("%d", &a);
		printf("Ingresa el segundo número: ");
		scanf("%d", &b);
		
		args.a = a;
		args.b = b;
		
		switch (operacion) {
			case 1: {
				int *result = suma_1(&args, clnt);
				if (result == NULL) {
					clnt_perror(clnt, "Error en suma");
				} else {
					printf("Resultado: %d + %d = %d\n", a, b, *result);
				}
				break;
			}
			case 2: {
				int *result = resta_1(&args, clnt);
				if (result == NULL) {
					clnt_perror(clnt, "Error en resta");
				} else {
					printf("Resultado: %d - %d = %d\n", a, b, *result);
				}
				break;
			}
			case 3: {
				int *result = multiplica_1(&args, clnt);
				if (result == NULL) {
					clnt_perror(clnt, "Error en multiplicación");
				} else {
					printf("Resultado: %d * %d = %d\n", a, b, *result);
				}
				break;
			}
			case 4: {
				double *result = divide_1(&args, clnt);
				if (result == NULL) {
					clnt_perror(clnt, "Error en división");
				} else if (isnan(*result)) {
					printf("Error: División por cero\n");
				} else {
					printf("Resultado: %d / %d = %.2f\n", a, b, *result);
				}
				break;
			}
		}
		printf("\n");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cal_prog_1 (host);
exit (0);
}
